name: GitHub Pages

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: BUILD_MODE=app npm run build -- --base=/login-client-vue/$BRANCH
        env:
          BRANCH: ${{ github.ref != 'refs/heads/main' && 'dev/' || '' }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          keep_files: true
          destination_dir: ${{ github.ref != 'refs/heads/main' && 'dev' || '' }}
